# Generated by Django 5.2.5 on 2025-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField()),
                ('mud_url', models.URLField()),
                ('provisioned', models.BooleanField(default=False)),
                ('status', models.CharField(default='OFF', max_length=10)),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
