# Generated by Django 5.2.5 on 2025-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='mud_url',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='provisioned',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='status',
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='mud_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='state',
            field=models.CharField(default='OFF', max_length=50),
        ),
    ]
