# Generated by Django 5.2.5 on 2025-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_iotdevice_mud_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='mud_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
