# Generated by Django 5.2.5 on 2025-09-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_iotdevice_mud_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='testcases_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='testcases_passed',
            field=models.IntegerField(default=0),
        ),
    ]
